//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Budget_Alex.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Budget
    {
        public int Id { get; set; }
        public Nullable<bool> IsEin { get; set; }
        public Nullable<bool> IsFixe { get; set; }
        public string Name { get; set; }
        public string Nr { get; set; }
        public double Summe { get; set; }
        public double SummeEffectiv { get; set; }
        public double SummeRest { get; set; }
        public System.DateTime DateCreate { get; set; }
        public System.DateTime DateChange { get; set; }
        public Nullable<short> Jahr { get; set; }
        public Nullable<short> Monate { get; set; }
        public string UserBudget { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
    }
}
