//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityBudget
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankKonto
    {
        public int Id { get; set; }
        public int SummeNew { get; set; }
        public int SummeRest { get; set; }
        public System.DateTime DateChange { get; set; }
    }
}
